import { execFile } from 'node:child_process';
import { createHash } from 'node:crypto';
import { promisify } from 'node:util';

import type { WorkerConfig } from './config.js';
import type { ExecutorArtifact, ExecutorRunResult, RemoteWorkerJob, SessionProvider } from './types.js';

const execFileAsync = promisify(execFile);

export interface PublishContext {
  job: RemoteWorkerJob;
  workerId: string;
  provider: SessionProvider;
  workspacePath: string;
  executionResult: ExecutorRunResult;
}

export interface PublishResult {
  summarySuffix?: string;
  resultJson?: Record<string, unknown>;
  artifacts?: ExecutorArtifact[];
}

export interface ResultPublisher {
  publish(context: PublishContext): Promise<PublishResult | null>;
}

interface GitHubRepoRef {
  owner: string;
  repo: string;
}

interface GitHubPullRequestResult {
  number: number;
  url: string;
}

interface GitStatusEntry {
  path: string;
}

function encodeInlineArtifact(
  kind: ExecutorArtifact['request']['kind'],
  contentType: string,
  content: string,
  metadata: Record<string, unknown> = {}
): ExecutorArtifact {
  const buffer = Buffer.from(content, 'utf8');
  return {
    request: {
      kind,
      storage_type: 'inline',
      content_type: contentType,
      content_base64: buffer.toString('base64'),
      sha256: createHash('sha256').update(buffer).digest('hex'),
      size_bytes: buffer.length,
      metadata
    }
  };
}

function withGitConfigOverride(env: NodeJS.ProcessEnv, key: string, value: string): NodeJS.ProcessEnv {
  const mergedEnv: NodeJS.ProcessEnv = {
    ...env
  };
  const existingCount = Number.parseInt(mergedEnv.GIT_CONFIG_COUNT ?? '0', 10);
  const safeCount = Number.isInteger(existingCount) && existingCount >= 0 ? existingCount : 0;
  const nextIndex = safeCount;

  mergedEnv.GIT_CONFIG_COUNT = String(safeCount + 1);
  mergedEnv[`GIT_CONFIG_KEY_${nextIndex}`] = key;
  mergedEnv[`GIT_CONFIG_VALUE_${nextIndex}`] = value;

  return mergedEnv;
}

function buildGitEnv(baseEnv: NodeJS.ProcessEnv, workspacePath: string): NodeJS.ProcessEnv {
  return withGitConfigOverride(baseEnv, 'safe.directory', workspacePath);
}

async function runGit(args: string[], cwd: string, env: NodeJS.ProcessEnv): Promise<string> {
  try {
    const { stdout } = await execFileAsync('git', args, {
      cwd,
      env
    });
    return stdout.trim();
  } catch (error) {
    const execError = error as NodeJS.ErrnoException & {
      stdout?: string;
      stderr?: string;
    };
    const stderr = execError.stderr?.trim();
    const stdout = execError.stdout?.trim();
    const detail = stderr || stdout || execError.message;
    throw new Error(`git ${args.join(' ')} failed${detail ? `: ${detail}` : ''}`);
  }
}

function sanitizeBranchSegment(input: string): string {
  return input.replace(/[^A-Za-z0-9._/-]+/g, '-').replace(/\/+/g, '/').replace(/^-+|-+$/g, '') || 'job';
}

function buildBranchName(prefix: string, jobId: string): string {
  return `${sanitizeBranchSegment(prefix)}/${sanitizeBranchSegment(jobId)}`;
}

function buildCommitMessage(job: RemoteWorkerJob): string {
  return `worker: apply ${job.job_id}`;
}

function buildPullRequestTitle(job: RemoteWorkerJob): string {
  return `worker: apply ${job.job_id}`;
}

function buildPullRequestBody(context: PublishContext, commitSha: string, branchName: string): string {
  const promptPreview =
    context.job.prompt.length > 400
      ? `${context.job.prompt.slice(0, 400)}...`
      : context.job.prompt;

  return [
    'Automated pull request generated by `remote-worker-agent`.',
    '',
    `- Job: \`${context.job.job_id}\``,
    `- Worker: \`${context.workerId}\``,
    `- Provider: \`${context.provider}\``,
    `- Base branch: \`${context.job.branch}\``,
    `- Base commit: \`${context.job.base_commit}\``,
    `- Publish branch: \`${branchName}\``,
    `- Commit: \`${commitSha}\``,
    '',
    'Prompt preview:',
    '',
    '```text',
    promptPreview,
    '```'
  ].join('\n');
}

function parseStatusEntries(stdout: string): GitStatusEntry[] {
  const entries: GitStatusEntry[] = [];

  for (const rawLine of stdout.split(/\r?\n/u)) {
    const line = rawLine.trimEnd();
    if (!line) {
      continue;
    }

    const payload = line.slice(3).trim();
    const path = payload.includes(' -> ') ? payload.split(' -> ').at(-1)! : payload;
    entries.push({ path });
  }

  return entries;
}

function isIgnoredPath(relativePath: string): boolean {
  return relativePath === 'job-manifest.json';
}

async function listRelevantStatusEntries(workspacePath: string, env: NodeJS.ProcessEnv): Promise<GitStatusEntry[]> {
  const stdout = await runGit(['status', '--porcelain=v1', '--untracked-files=all'], workspacePath, env);
  return parseStatusEntries(stdout).filter((entry) => !isIgnoredPath(entry.path));
}

export function parseGitHubRepoRef(repoUrl: string): GitHubRepoRef | null {
  const sshMatch = repoUrl.match(/^git@github\.com:([^/]+)\/(.+?)(?:\.git)?$/u);
  if (sshMatch) {
    return {
      owner: sshMatch[1],
      repo: sshMatch[2]
    };
  }

  const httpsMatch = repoUrl.match(/^https:\/\/github\.com\/([^/]+)\/(.+?)(?:\.git)?$/u);
  if (httpsMatch) {
    return {
      owner: httpsMatch[1],
      repo: httpsMatch[2]
    };
  }

  return null;
}

async function createGitHubPullRequest(options: {
  apiBaseUrl: string;
  token: string;
  repo: GitHubRepoRef;
  branchName: string;
  baseBranch: string;
  title: string;
  body: string;
  draft: boolean;
}): Promise<GitHubPullRequestResult> {
  const response = await fetch(`${options.apiBaseUrl}/repos/${options.repo.owner}/${options.repo.repo}/pulls`, {
    method: 'POST',
    headers: {
      authorization: `Bearer ${options.token}`,
      accept: 'application/vnd.github+json',
      'content-type': 'application/json'
    },
    body: JSON.stringify({
      title: options.title,
      head: `${options.repo.owner}:${options.branchName}`,
      base: options.baseBranch,
      body: options.body,
      draft: options.draft
    })
  });

  if (response.status === 422) {
    const existingResponse = await fetch(
      `${options.apiBaseUrl}/repos/${options.repo.owner}/${options.repo.repo}/pulls?state=open&head=${encodeURIComponent(
        `${options.repo.owner}:${options.branchName}`
      )}`,
      {
        headers: {
          authorization: `Bearer ${options.token}`,
          accept: 'application/vnd.github+json'
        }
      }
    );

    if (!existingResponse.ok) {
      throw new Error(`GitHub pull request lookup failed with status ${existingResponse.status}`);
    }

    const existing = (await existingResponse.json()) as Array<{ number: number; html_url: string }>;
    if (existing.length > 0) {
      return {
        number: existing[0].number,
        url: existing[0].html_url
      };
    }
  }

  if (!response.ok) {
    const body = await response.text();
    throw new Error(`GitHub pull request creation failed with status ${response.status}: ${body}`);
  }

  const data = (await response.json()) as { number: number; html_url: string };
  return {
    number: data.number,
    url: data.html_url
  };
}

export class GitResultPublisher implements ResultPublisher {
  constructor(private readonly config: WorkerConfig) {}

  async publish(context: PublishContext): Promise<PublishResult | null> {
    if (this.config.publishMode === 'artifact') {
      return null;
    }

    const env = buildGitEnv(
      {
        ...process.env,
        ...this.config.gitEnv
      },
      context.workspacePath
    );

    const relevantChanges = await listRelevantStatusEntries(context.workspacePath, env);
    if (relevantChanges.length === 0) {
      return {
        resultJson: {
          publish: {
            mode: this.config.publishMode,
            skipped: 'no_changes'
          }
        },
        artifacts: [
          encodeInlineArtifact(
            'report',
            'application/json',
            `${JSON.stringify(
              {
                publish_mode: this.config.publishMode,
                skipped: 'no_changes'
              },
              null,
              2
            )}\n`,
            { stage: 'publish' }
          )
        ]
      };
    }

    const repoRef = parseGitHubRepoRef(context.job.repo_url);
    let prRepoRef: GitHubRepoRef | null = null;
    let githubToken: string | undefined;
    if (this.config.publishMode === 'pr') {
      if (!repoRef) {
        throw new Error(`Cannot create PR for non-GitHub repository URL: ${context.job.repo_url}`);
      }

      if (!this.config.githubToken) {
        throw new Error('GitHub token is required when WORKER_PUBLISH_MODE=pr');
      }

      prRepoRef = repoRef;
      githubToken = this.config.githubToken;
    }

    const branchName = buildBranchName(this.config.publishBranchPrefix, context.job.job_id);
    const commitMessage = buildCommitMessage(context.job);

    await runGit(['checkout', '-B', branchName], context.workspacePath, env);
    await runGit(['config', 'user.name', this.config.gitCommitName], context.workspacePath, env);
    await runGit(['config', 'user.email', this.config.gitCommitEmail], context.workspacePath, env);
    await runGit(['add', '-A', '.'], context.workspacePath, env);
    await runGit(['reset', '--', 'job-manifest.json'], context.workspacePath, env).catch(() => {});

    const stagedChanges = await runGit(['diff', '--cached', '--name-only'], context.workspacePath, env);
    if (!stagedChanges.trim()) {
      return {
        resultJson: {
          publish: {
            mode: this.config.publishMode,
            skipped: 'no_changes'
          }
        }
      };
    }

    await runGit(['commit', '-m', commitMessage], context.workspacePath, env);
    const commitSha = await runGit(['rev-parse', 'HEAD'], context.workspacePath, env);
    await runGit(['push', '-u', 'origin', branchName], context.workspacePath, env);

    const checksUrl =
      repoRef ? `https://github.com/${repoRef.owner}/${repoRef.repo}/commit/${commitSha}/checks` : null;

    let pullRequest: GitHubPullRequestResult | null = null;
    if (this.config.publishMode === 'pr') {
      pullRequest = await createGitHubPullRequest({
        apiBaseUrl: this.config.githubApiBaseUrl,
        token: githubToken!,
        repo: prRepoRef!,
        branchName,
        baseBranch: context.job.branch,
        title: buildPullRequestTitle(context.job),
        body: buildPullRequestBody(context, commitSha, branchName),
        draft: this.config.githubPrDraft
      });
    }

    const publishReport = {
      mode: this.config.publishMode,
      branch_name: branchName,
      commit_sha: commitSha,
      commit_message: commitMessage,
      checks_url: checksUrl,
      pull_request: pullRequest
        ? {
            number: pullRequest.number,
            url: pullRequest.url
          }
        : null
    };

    return {
      summarySuffix: pullRequest
        ? `PR: ${pullRequest.url}`
        : `branch=${branchName} commit=${commitSha}`,
      resultJson: {
        publish: publishReport
      },
      artifacts: [
        encodeInlineArtifact('report', 'application/json', `${JSON.stringify(publishReport, null, 2)}\n`, {
          stage: 'publish'
        })
      ]
    };
  }
}
